#!/usr/bin/env zsh

# Create a new directory and enter it
mkd() {
  mkdir -p "$@" && cd "$_"
}

# Change working directory to the top-most Finder window location
cdf() { # short for `cdfinder`
  cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')"
}

# `o` with no arguments opens the current directory, otherwise opens the given
# location
o() {
  if [ $# -eq 0 ]; then
    open .
  else
    open "$@"
  fi
}

# capture output from process id
capture() {
  sudo dtrace -p "$1" -qn '
        syscall::write*:entry
        /pid == $target && arg0 == 1/ {
            printf("%s", copyinstr(arg1, arg2));
        }
    '
}

is_git() {
  [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) == true ]]
}

set_name() {
  local CMD=$2

  local "BETTER_PWD"
  if is_git; then
    BETTER_PWD=$(git rev-parse --show-toplevel)
  else
    BETTER_PWD=$(PWD)
  fi

  BETTER_PWD="${BETTER_PWD#"$HOME/Projects"/}"
  BETTER_PWD="${BETTER_PWD#"$HOME"/~}"

  if [ -z "$CMD" ]; then
    echo -ne "\033]0;${BETTER_PWD##*/}\007"
  else
    echo -ne "\033]0;${BETTER_PWD##*/} (${CMD})\007"
  fi
}

precmd_functions+=(set_name)
preexec_functions+=(set_name)
